# -*- coding: utf-8 -*-
"""diarioextra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-XFzk5Fk30VnAHJflbOwEqvdyvzOP04
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
import json
from datetime import datetime

# --- Configuración ---
BASE_URL = 'https://www.diarioextra.com'
# URLs corregidas basadas en el menú
SECTIONS = {
    'principal': 'https://www.diarioextra.com/',
    'ultimas_noticias': 'https://www.diarioextra.com/categoria/ultimas-noticias',
    'nacionales': 'https://www.diarioextra.com/categoria/nacionales',
    'deportes': 'https://www.diarioextra.com/categoria/deportes',
    'sucesos': 'https://www.diarioextra.com/categoria/sucesos',
    'internacionales': 'https://www.diarioextra.com/categoria/internacionales',
    'opinion': 'https://www.diarioextra.com/categoria/opinion'
}
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.0

def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    """Elimina espacios/saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup, url):
    """
    Extrae título, fecha, autor y contenido desde la página interna del artículo.
    """
    # --- Título ---
    title_tag = soup.find('h1', class_='single-layout__title')
    if not title_tag:
        title_tag = soup.find('h1')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin título"

    # --- Subtítulo ---
    excerpt_tag = soup.find('h2', class_='single-layout__excerpt')
    excerpt = clean_text(excerpt_tag.get_text()) if excerpt_tag else ""

    # --- Categoría y fecha (el sitio las publica vía JSON-LD, no en el HTML) ---
    category = "Sin categoría"
    date = "Sin fecha"
    for script_tag in soup.find_all('script', type='application/ld+json'):
        try:
            ld_data = json.loads(script_tag.string)
        except (TypeError, ValueError):
            continue
        graph = ld_data.get('@graph', [ld_data]) if isinstance(ld_data, dict) else ld_data
        for item in graph:
            if isinstance(item, dict) and item.get('@type') in ('NewsArticle', 'Article'):
                if item.get('datePublished'):
                    date = item['datePublished']
                sections = item.get('articleSection')
                if sections:
                    category = sections[0] if isinstance(sections, list) else sections
                break

    # Fallback a los selectores HTML antiguos por si el sitio los reintroduce
    if category == "Sin categoría":
        category_tag = soup.find('div', class_='single-layout__meta-taxonomy')
        category = clean_text(category_tag.get_text()) if category_tag else category
    if date == "Sin fecha":
        date_tag = soup.find('div', class_='single-layout__meta-date')
        date = clean_text(date_tag.get_text()) if date_tag else date

    # --- Autor ---
    author_tag = soup.find('a', class_='single-layout__author')
    author = clean_text(author_tag.get_text()) if author_tag else "Sin autor"

    # --- Contenido ---
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_='single-layout__article')
    if not content_div:
        # Una petición sin JavaScript (requests) recibe la versión sin scripts de la
        # página, donde el cuerpo vive en div.noscript__content (con JS es el de arriba).
        content_div = soup.find('div', class_='noscript__content')

    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'ins', 'figure', 'blockquote']):
            tag.decompose()
        for ad in content_div.find_all('div', class_=lambda x: x and 'ned-ad' in x):
            ad.decompose()

        paragraphs = content_div.find_all('p')
        if paragraphs:
            content = ' '.join([clean_text(p.get_text()) for p in paragraphs if p.get_text().strip()])
        else:
            content = clean_text(content_div.get_text())

    if excerpt and content != "Contenido no encontrado":
        content = excerpt + " " + content

    return title, author, date, content, category

def get_article_links(soup):
    """Extrae todos los enlaces de artículos."""
    links = []

    for a_tag in soup.find_all('a', href=True):
        href = a_tag['href']

        # Buscar enlaces con /noticia/
        if '/noticia/' in href.lower():
            if href.startswith('/'):
                href = BASE_URL + href
            if 'diarioextra.com' in href and href not in links:
                links.append(href)

    return links

# -------------------------------------------------------
# PASO 1: Leer secciones → extraer enlaces
# -------------------------------------------------------
data = []
all_links = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print("=" * 70)
    print("📰 WEB SCRAPING - DIARIO EXTRA")
    print("=" * 70)

    # Primero solo la página principal (que siempre funciona)
    print(f"\n📂 Leyendo: PÁGINA PRINCIPAL")
    main_soup = get_soup(BASE_URL, session)

    if main_soup:
        links = get_article_links(main_soup)
        print(f"   ✅ {len(links)} enlaces encontrados")
        all_links.extend(links)

    time.sleep(DELAY)

    # Intentar otras secciones
    for section_name, section_url in SECTIONS.items():
        if section_name == 'principal':
            continue

        print(f"\n📂 Leyendo: {section_name.upper()}")
        section_soup = get_soup(section_url, session)

        if section_soup:
            links = get_article_links(section_soup)
            print(f"   ✅ {len(links)} enlaces encontrados")
            all_links.extend(links)
        else:
            print(f"   ⚠️ Sección no accesible, continuando...")

        time.sleep(DELAY)

    # Eliminar duplicados
    all_links = list(set(all_links))
    print(f"\n🔗 Total de enlaces únicos: {len(all_links)}")

    # -------------------------------------------------------
    # PASO 2: Extraer datos de cada artículo
    # -------------------------------------------------------
    if len(all_links) > 0:
        print("\n" + "=" * 70)
        print(f"📰 Extrayendo {len(all_links)} artículos...")
        print("=" * 70 + "\n")

        for i, link in enumerate(all_links, 1):
            slug = link.rstrip('/').split('/')[-1][:50]
            print(f"  [{i}/{len(all_links)}] Procesando: {slug}...")

            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, author, date, content, category = extract_article_data(article_soup, link)
            else:
                title, author, date, content, category = "Error", "Error", "Error", "Error al recuperar", "error"

            data.append({
                'source':           'diarioextra',
                'url':              link,
                'title':            title,
                'author':           author,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          category,
                'full_text':        content,
                'language':         'es'
            })
    else:
        print("\n⚠️ No se encontraron enlaces.")

# -------------------------------------------------------
# PASO 3: DataFrame final
# -------------------------------------------------------
df = pd.DataFrame(data)

print("\n" + "=" * 70)
print(f"📊 DataFrame: {len(df)} filas × {len(df.columns)} columnas")
print("=" * 70)

df.to_csv('diarioextra.csv', index=False, encoding='utf-8-sig')
print(f"\n💾 Archivo guardado: diarioextra.csv")

try:
    from google.colab import files
except ImportError:
    files = None
if files:
    files.download('diarioextra.csv')