# -*- coding: utf-8 -*-
"""Periódico Mi Tierra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTCVt4oW88zwq2Iv9s7s9oIwi9Ag7GgM
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# --- Configuración ---
BASE_URL = 'https://periodicomitierra.com'
SECCIONES = {
    'noticias':    '/actualidad/noticias',
    'politica':    '/actualidad/politica',
    'salud':       '/actualidad/salud',
    'cultura':     '/actualidad/cultura',
    'sucesos':     '/actualidad/sucesos',
    'deportes':    '/actualidad/deportes',
    'editorial':   '/opinion/editorial',
    'columnistas': '/opinion/columnistas',
}
HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha y contenido del artículo.
    Estructura HTML de periodicomitierra.com (Drupal):
      - Título:    <h2 class="col title"><span>
      - Fecha:     <time class="datetime" datetime="YYYY-MM-DDTHH:MM:SSZ">
      - Contenido: <div class="wrapper-content">
    """
    # Título
    title = "Sin titulo"
    h2 = soup.find('h2', class_='col title') or soup.find('h2', class_='title')
    if h2:
        span = h2.find('span')
        title = clean_text(span.get_text() if span else h2.get_text())

    # Fecha
    date = "Sin fecha"
    time_tag = soup.find('time', class_='datetime')
    if time_tag:
        dt = time_tag.get('datetime', '')
        date = dt[:10] if dt else "Sin fecha"

    # Contenido
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_='wrapper-content')
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'figure', 'aside']):
            tag.decompose()
        content = clean_text(content_div.get_text())

    return title, date, content

# --- Scraping principal ---
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, path in SECCIONES.items():
        url = BASE_URL + path
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for span in main_soup.find_all('span', class_='title'):
            a = span.find('a', href=True)
            if a:
                href = a['href']
                link = href if href.startswith('http') else BASE_URL + href
                # El sitio a veces enlaza la misma nota con /index.php/; se guarda siempre la URL canónica
                link = link.replace('/index.php/', '/')
                if link not in urls_vistas:
                    links.append(link)
                    urls_vistas.add(link)

        print(f"  {len(links)} articulos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-1][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, content = extract_article_data(article_soup)
            else:
                title, date, content = "Error", "Error", "Error al recuperar"

            data.append({
                'source':           'mitierra',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })

# --- DataFrame final ---
df_mitierra = pd.DataFrame(data).drop_duplicates(subset='url')
print(f"\nDataFrame: {len(df_mitierra)} filas x {len(df_mitierra.columns)} columnas")
df_mitierra.head(8)

_today = datetime.now().strftime('%Y%m%d')
_out_file = f'mitierra_{_today}.csv'
df_mitierra.to_csv(_out_file, index=False, encoding='utf-8', sep=',', na_rep='NULL')
print(f"Archivo guardado: {_out_file}")

try:
    from google.colab import files
except ImportError:
    files = None
if files:
    files.download(_out_file)